### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Julien-Broyard/type-graphql-api#1]
Hi @Julien-Broyard  I finished the design already and here it is! I hope that you will like it again.. 😃

![PRES-01-01](https://user-images.githubusercontent.com/36028424/55961568-bce31700-5ca1-11e9-98bf-9e99c0cc9f2b.png)

**Comment by Julien-Broyard** [comment]
Wow :open_mouth:

**Comment by Tobaloidee** [comment]
😀 will finish the files again and make a PR 👍

**Comment by Julien-Broyard** [comment]
Can't thank you enough :smile:

**Comment by Tobaloidee** [comment]
Here's the PR #2 @Julien-Broyard  and here is the [LINK](https://drive.google.com/drive/u/1/folders/1AFUYPLa9MfnOsYvqtHoDMW4b5qU2JKVh) to the other versions and formats! Thanks so much!! it has been a pleasure working for your projects! 

Best regards!

-Tobaloidee

**Comment by Tobaloidee** [comment]
I'll be closing all the issues I have created.
